import React from "react";
import { ClerkProvider, SignedIn, SignedOut, UserButton, currentUser } from "@clerk/nextjs/app-beta";

import './globals.scss';

import { Inter } from 'next/font/google';

import Link from "next/link";

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const RootLayout : ({ children } : { children : React.ReactNode }) => JSX.Element = ({ children }) => {
	return (
		<ClerkProvider>
			<html lang="en">
				<body className={inter.className}>
					<div className="Navigation">
						<nav>
							<Link href={ "/" }>Home</Link>

							<SignedIn>
								<Link href={ "/profile/" }>Profile</Link>

								<UserButton></UserButton>
							</SignedIn>

							<SignedOut>
								<Link href={ "/signin/" }>Sign in</Link>

								<Link href={ "/signup/" }>Sign up</Link>
							</SignedOut>
						</nav>
					</div>

					{children}
				</body>
			</html>
		</ClerkProvider>
	)
};
export default RootLayout;