import { currentUser } from "@clerk/nextjs/app-beta";
import "@/styles/page.module.scss";
import Heading from "@/components/ui/Heading";
import Paragraph from "@/components/ui/Paragraph";
import Test from "@/components/Test";
import { Metadata } from "next";

export const metadata : Metadata = {
	title: 'Home page',
	description: 'Generated by create next app',
};

const HomePage : () => Promise<JSX.Element> = async () => {
	const user = await currentUser();

	return (
		<main id="HomePage">
			<Heading varient="h1">Home Page</Heading>

			<div>
				<Paragraph>{ JSON.stringify(user) }</Paragraph>
			</div>

			<Test />
		</main>
	)
};
export default HomePage;